---
- hosts: all
  tasks:
   - name: installation baseline compliance
     yum: 
        name:
          -sysstat
          -httpd
          -vim
          -unzip
          -curl
        state: latest
